CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS vtc_drivers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  slug text UNIQUE NOT NULL,
  display_name text NOT NULL,
  first_name text,
  bio text,
  other_activities text[] NOT NULL DEFAULT '{}',
  languages text[] NOT NULL DEFAULT '{}',
  interests text[] NOT NULL DEFAULT '{}',
  phone text,
  email text,
  website text,
  vcard text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE vtc_drivers
  ADD COLUMN IF NOT EXISTS driver_number bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS vtc_drivers_driver_number_idx
  ON vtc_drivers(driver_number);

ALTER TABLE vtc_drivers ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE vtc_drivers ADD COLUMN IF NOT EXISTS bio text;
ALTER TABLE vtc_drivers ADD COLUMN IF NOT EXISTS other_activities text[] NOT NULL DEFAULT '{}';
ALTER TABLE vtc_drivers ADD COLUMN IF NOT EXISTS languages text[] NOT NULL DEFAULT '{}';
ALTER TABLE vtc_drivers ADD COLUMN IF NOT EXISTS interests text[] NOT NULL DEFAULT '{}';
ALTER TABLE vtc_drivers ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE vtc_drivers ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE vtc_drivers ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE vtc_drivers ADD COLUMN IF NOT EXISTS vcard text;

CREATE TABLE IF NOT EXISTS vtc_driver_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  driver_id uuid NOT NULL REFERENCES vtc_drivers(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('service', 'favorite')),
  title text NOT NULL CHECK (char_length(title) BETWEEN 1 AND 100),
  description text NOT NULL CHECK (char_length(description) BETWEEN 1 AND 500),
  address text,
  price_cents integer CHECK (price_cents IS NULL OR price_cents >= 0),
  currency char(3) NOT NULL DEFAULT 'EUR',
  display_order integer NOT NULL DEFAULT 0,
  is_visible boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE vtc_driver_content
  ADD COLUMN IF NOT EXISTS price_cents integer
  CHECK (price_cents IS NULL OR price_cents >= 0);

ALTER TABLE vtc_driver_content
  ADD COLUMN IF NOT EXISTS currency char(3) NOT NULL DEFAULT 'EUR';

CREATE INDEX IF NOT EXISTS vtc_driver_content_driver_kind_idx
  ON vtc_driver_content(driver_id, kind, display_order)
  WHERE is_visible = true;

INSERT INTO vtc_drivers (slug, display_name)
VALUES ('demo', 'Votre chauffeur Welcome')
ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name;

UPDATE vtc_drivers
SET first_name = COALESCE(first_name, 'Alexandre'),
    bio = COALESCE(bio, 'Chauffeur professionnel attentif, je veille à rendre chaque trajet agréable et serein.'),
    other_activities = CASE WHEN cardinality(other_activities) = 0
      THEN ARRAY['Entrepreneur', 'Ambassadeur local'] ELSE other_activities END,
    languages = CASE WHEN cardinality(languages) = 0
      THEN ARRAY['Français', 'Anglais', 'Allemand'] ELSE languages END,
    interests = CASE WHEN cardinality(interests) = 0
      THEN ARRAY['Voyages', 'Gastronomie', 'Patrimoine régional'] ELSE interests END,
    phone = COALESCE(phone, '+33 6 22 80 55 36'),
    email = COALESCE(email, 'contact@welcome-coworking.com'),
    website = COALESCE(website, 'https://www.welcome-coworking.com'),
    vcard = COALESCE(vcard, E'BEGIN:VCARD\r\nVERSION:3.0\r\nFN:Votre chauffeur Welcome\r\nN:;Alexandre;;;\r\nTEL;TYPE=CELL:+33 6 22 80 55 36\r\nEMAIL;TYPE=INTERNET:contact@welcome-coworking.com\r\nURL:https://www.welcome-coworking.com\r\nNOTE:Chauffeur professionnel attentif, je veille à rendre chaque trajet agréable et serein.\r\nEND:VCARD')
WHERE slug = 'demo';

INSERT INTO vtc_driver_content (driver_id, kind, title, description, display_order)
SELECT id, 'service', 'Bouteilles d’eau à disposition',
       'Une bouteille d’eau individuelle peut vous être proposée pendant le trajet.', 10
FROM vtc_drivers
WHERE slug = 'demo'
  AND NOT EXISTS (
    SELECT 1 FROM vtc_driver_content c
    WHERE c.driver_id = vtc_drivers.id AND c.kind = 'service'
      AND c.title = 'Bouteilles d’eau à disposition'
  );

INSERT INTO vtc_driver_content
  (driver_id, kind, title, description, price_cents, currency, display_order)
SELECT id, 'service', 'Chewing-gum', 'Un paquet Freedent menthe ou fraîcheur.', 200, 'EUR', 20
FROM vtc_drivers
WHERE slug = 'demo'
  AND NOT EXISTS (
    SELECT 1 FROM vtc_driver_content c
    WHERE c.driver_id = vtc_drivers.id AND c.kind = 'service'
      AND c.title = 'Chewing-gum'
  );

INSERT INTO vtc_driver_content
  (driver_id, kind, title, description, address, display_order)
SELECT id, 'favorite', 'La Corde à Linge',
       'Une adresse conviviale appréciée du chauffeur au cœur de la Petite France.',
       '2 place Benjamin-Zix, 67000 Strasbourg', 10
FROM vtc_drivers
WHERE slug = 'demo'
  AND NOT EXISTS (
    SELECT 1 FROM vtc_driver_content c
    WHERE c.driver_id = vtc_drivers.id AND c.kind = 'favorite'
      AND c.title = 'La Corde à Linge'
  );
